steps:
# - name: 'gcr.io/cloud-builders/gsutil'
#   id: copy_config
#   waitFor: ['-']  # The '-' indicates that this step begins immediately.
#   # we use rsync and not cp so that this step doesn't fail the first time it's run
#   args: ['rsync', 'gs://myiac_base/', '/myiac_base']
#   volumes:
#   - name: 'myiac_base'
#     path: '/myiac_base'

- id: go_version
  name: golang
  args: ["go", "version"]

- name: golang
  args: ['go', 'build', '-o', 'myiac', 'github.com/dfernandezm/myiac/app']
  env: ['GO111MODULE=on']

# - id: go_dependencies
#   name: "gcr.io/cloud-builders/go"
#   args: ["get", "-d", "-v", "./..."]
#   env: ["GOPATH=."]

# - id: go_install
#   name: "gcr.io/cloud-builders/go"
#   args: ["install","-v","./..."]
#   env: ["GOPATH=."]

# - name: "gcr.io/cloud-builders/go"
#   args: ['go', 'build', '-o', 'myiac', 'app']

# - name: 'gcr.io/$PROJECT_ID/tar'
#   id: setup_env
#   entrypoint: 'bash'
#   args: 
#   - '-c'
#   - |
#     ls -la /myiac_base
#   waitFor: ['copy_config']
#   volumes:
#   - name: 'myiac_base'
#     path: '/myiac_base'
artifacts:
  objects:
    location: 'gs://myiac-base/'
    paths: ['myiac']

